export const IMPORT_SUCCESS = 'msg.success.load'; // json key
export const PARSE_FAILE = 'msg.err.PARSE_FAILE';
export const JSON_PARSE_FAILE = 'msg.err.jsonparse'; // json key
export const XML_PARSE_FAILE = 'msg.err.xmlparse';
export const FILE_TYPE_ERROR = 'msg.err.file.type';
export const FORM_TYPE_ERROR = 'msg.err.form.type';
export const CHECK_SUM_ERROR = 'msg.err.CHECK_SUM_FAIL';
export const DRAFT_FILE_TYPE = 'hcsc';
export const FINAL_FILE_TYPE = 'xml';
